name: chatsample
description: XMPP Chat with Queue management

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  connectivity: ^0.4.3+1
  provider: ^2.0.1
  rxdart: ^0.18.0
  bubble: ^1.1.9+1
  font_awesome_flutter: ^8.8.1
  path_provider: ^2.0.8
  sqflite: ^2.0.1
  random_string: ^2.0.1
  shared_preferences: ^2.0.11
  flutter_launcher_icons: ^0.9.2
  time_formatter: ^1.0.0
  intl: ^0.16.1
  flutter_speed_dial: ^1.2.5
  image_picker:
  permission_handler: ^8.3.0
  sizer: ^2.0.15
  xmpp_plugin: ^2.1.1
  flutter_isolate: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/applogo.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter:
  uses-material-design: true
  assets:
    - assets/
